"""add trip map lat lng

Revision ID: 3941da7f1f70
Revises: 638b8bd99663
Create Date: 2026-08-12 07:58:02.971466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3941da7f1f70'
down_revision: Union[str, None] = '638b8bd99663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('origin_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('origin_lng', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_lng')
    op.drop_column('trips', 'destination_lat')
    op.drop_column('trips', 'origin_lng')
    op.drop_column('trips', 'origin_lat')
    # ### end Alembic commands ###
