"""add trip high demand flag

Revision ID: 663ad67d0dbf
Revises: eeefd5b0bd97
Create Date: 2026-08-02 15:35:19.444631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663ad67d0dbf'
down_revision: Union[str, None] = 'eeefd5b0bd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('ai_high_demand', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'ai_high_demand')
    # ### end Alembic commands ###
