"""add reservation passenger contact columns

Revision ID: 69343350a5b0
Revises: 663ad67d0dbf
Create Date: 2026-08-05 12:24:08.630885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69343350a5b0'
down_revision: Union[str, None] = '663ad67d0dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('passenger_name', sa.String(length=120), nullable=True))
    op.add_column('reservations', sa.Column('passenger_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'passenger_phone')
    op.drop_column('reservations', 'passenger_name')
    # ### end Alembic commands ###
