"""add reservation accessibility columns

Revision ID: eeefd5b0bd97
Revises: 32a243581b97
Create Date: 2026-08-02 15:11:17.591928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeefd5b0bd97'
down_revision: Union[str, None] = '32a243581b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('accessibility_note', sa.String(length=500), nullable=True))
    op.add_column('reservations', sa.Column('ai_accessibility_tags', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'ai_accessibility_tags')
    op.drop_column('reservations', 'accessibility_note')
    # ### end Alembic commands ###
